//! HTTP 路由处理器。

use axum::{routing::{delete, get, post, put}, Router};

use crate::state::AppState;

pub mod auth;
pub mod attachments;
pub mod admin;
pub mod exports;
pub mod students;
pub mod records;
pub mod forms;
pub mod profile;

/// 构建应用路由。
pub fn router(state: AppState) -> Router {
    Router::new()
        .route("/health", get(auth::health))
        .route("/auth/bootstrap/status", get(auth::bootstrap_status))
        .route("/auth/bootstrap", post(auth::bootstrap_admin))
        .route("/auth/config", get(auth::auth_config))
        .route("/auth/login/options", get(auth::login_options))
        .route("/auth/password-policy", get(auth::password_policy))
        .route("/auth/reauth/password", post(auth::reauth_password))
        .route("/auth/reauth/totp", post(auth::reauth_totp))
        .route("/auth/reauth/passkey/start", post(auth::reauth_passkey_start))
        .route("/auth/reauth/passkey/finish", post(auth::reauth_passkey_finish))
        .route("/auth/passkey/register/start", post(auth::passkey_register_start))
        .route("/auth/passkey/register/finish", post(auth::passkey_register_finish))
        .route("/auth/passkey/login/start", post(auth::passkey_login_start))
        .route("/auth/passkey/login/finish", post(auth::passkey_login_finish))
        .route("/auth/password/login", post(auth::password_login))
        .route("/auth/me", get(auth::current_user))
        .route("/auth/logout", post(auth::logout))
        .route("/auth/totp/enroll/start", post(auth::totp_enroll_start))
        .route("/auth/totp/enroll/finish", post(auth::totp_enroll_finish))
        .route("/auth/totp/verify", post(auth::totp_verify))
        .route("/auth/recovery/verify", post(auth::recovery_verify))
        .route("/auth/email/bind", post(auth::bind_email))
        .route("/auth/password/change", post(auth::change_password))
        .route("/auth/password/reset/request", post(auth::password_reset_request))
        .route("/auth/password/reset/confirm", post(auth::password_reset_confirm))
        .route("/auth/invite/status", get(auth::invite_status))
        .route("/auth/invite/accept", post(auth::invite_accept))
        .route("/auth/reset/status", get(auth::reset_status))
        .route("/auth/reset/consume", post(auth::reset_consume))
        .route("/auth/devices", get(auth::list_devices))
        .route("/auth/devices/:device_id", delete(auth::delete_device))
        .route("/profile/signature", get(profile::get_signature).post(profile::upload_signature))
        .route("/forms/:form_type/fields", get(forms::list_form_fields_for_type))
        .route("/competitions", get(admin::list_competitions_public))
        .route("/students", post(students::create_student))
        .route("/students/me", get(students::get_current_student))
        .route("/students/:student_no", put(students::update_student))
        .route("/students/query", post(students::list_students))
        .route("/students/import", post(students::import_students))
        .route("/records/contest", post(records::create_contest_record))
        .route("/records/contest/query", post(records::list_contest_records))
        .route("/records/contest/:record_id/review", post(records::review_contest_record))
        .route("/attachments/contest/:record_id", post(attachments::upload_contest_attachment))
        .route("/attachments/:attachment_id", get(attachments::download_attachment))
        .route("/signatures/:record_type/:record_id/:stage", post(attachments::upload_review_signature))
        .route("/export/summary/excel", post(exports::export_summary_excel))
        .route("/export/student/:student_no/excel", post(exports::export_student_excel))
        .route("/export/record/:record_type/:record_id/pdf", post(exports::export_record_pdf))
        .route("/export/labor-hours/:student_no/pdf", post(exports::export_labor_hours_pdf))
        .route("/export/labor-hours/summary/excel", post(exports::export_labor_hours_summary_excel))
        .route("/admin/competitions", get(admin::list_competitions))
        .route("/admin/competitions", post(admin::create_competition))
        .route("/admin/competitions/:competition_id", put(admin::update_competition))
        .route("/admin/competitions/:competition_id", delete(admin::delete_competition))
        .route("/admin/competitions/import", post(admin::import_competitions))
        .route("/admin/users", post(admin::create_user))
        .route("/admin/users/reset/totp", post(admin::reset_user_totp))
        .route("/admin/users/reset/passkey", post(admin::reset_user_passkey))
        .route("/admin/users/reset/code", post(admin::generate_reset_code))
        .route("/admin/password-policy", get(admin::get_password_policy))
        .route("/admin/password-policy", post(admin::update_password_policy))
        .route("/admin/labor-hour-rules", get(admin::get_labor_hour_rules))
        .route("/admin/labor-hour-rules", post(admin::update_labor_hour_rules))
        .route("/admin/form-fields", get(admin::list_form_fields))
        .route("/admin/form-fields", post(admin::create_form_field))
        .route("/admin/export-templates/:template_key", get(admin::get_export_template))
        .route("/admin/export-templates/:template_key/upload", post(admin::upload_export_template))
        .route("/admin/deleted/students", get(admin::list_deleted_students))
        .route("/admin/deleted/records/contest", get(admin::list_deleted_contest_records))
        .route("/admin/students/:student_no", delete(admin::delete_student))
        .route("/admin/students/:student_no/restore", post(admin::restore_student))
        .route("/admin/students/:student_no/allow-login", post(admin::update_student_login))
        .route("/admin/students/:student_no/reset-password", post(admin::reset_student_password))
        .route("/admin/students/create-users", post(admin::create_student_users))
        .route("/admin/records/contest/:record_id", delete(admin::delete_contest_record))
        .route("/admin/records/contest/:record_id/restore", post(admin::restore_contest_record))
        .route("/admin/purge/students/:student_no", delete(admin::purge_student))
        .route("/admin/purge/records/contest/:record_id", delete(admin::purge_contest_record))
        .route("/admin/records/contest/import", post(admin::import_contest_records))
        .with_state(state)
}
